name: bsrt
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.7
  - pip==22.2.2

  # Pulls in cudatoolkit
  - pytorch==1.12.1=py3.7_cuda11.6_cudnn8.3.2_0
  - torchvision==0.13.1=py37_cu116

  # Used to be installed by pip
  - matplotlib
  - imageio
  - opencv
  - tensorboardx
  - tqdm
  - timm
  - requests
  - exifread

  - pip:
    - torchsummaryX
    - pytorch-msssim
    - lpips
