[build-system]
requires = ["setuptools >= 65", "wheel"]

[project]
name = "bsrt"
version = "0.1.0"
description = "Multi-frame super-resolution tool"
authors = [{ name = "Ziwei Luo", email = "ziwei.ro@gmail.com" }]
maintainers = [
    { name = "Ziwei Luo", email = "ziwei.ro@gmail.com" },
    { name = "Connor Baker", email = "connorbaker01@gmail.com" },
]
readme = "README.md"
urls = { homepage = "https://github.com/connorbaker/bsrt" }
requires-python = ">=3.10"
dependencies = [
    "torch[dynamo]==1.14.0.dev20221119+cu117",
    "torchvision==0.15.0.dev20221119+cu117",
    "opencv-python-headless==4.6.0.66",
    "pytorch-lightning==1.8.2",
    "torchmetrics[image]==0.10.3",
    "wandb==0.13.5",
]

[project.optional-dependencies]
tune = [
    "syne-tune[gpsearchers] @ git+https://github.com/awslabs/syne-tune.git@db591a7ec1571a267725da1c2ce422e27f22874f",
]
lint = ["black==22.10.0", "flake8==6.0.0", "isort==5.10.1", "pyright==1.1.281"]

[tool.black]
line-length = 99
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 99
py_version = "39" # 3.10 isn't supported yet

[tool.setuptools]
packages = ["bsrt"]

[tool.pyright]
include = ["bsrt"]
exclude = ["**/__pycache__"]
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.10"
pythonPlatform = "Linux"
