[build-system]
requires = ["setuptools >= 65", "wheel"]

[project]
name = "bsrt"
version = "0.1.0"
description = "Multi-frame super-resolution tool"
authors = [{ name = "Ziwei Luo", email = "ziwei.ro@gmail.com" }]
maintainers = [
    { name = "Ziwei Luo", email = "ziwei.ro@gmail.com" },
    { name = "Connor Baker", email = "connorbaker01@gmail.com" },
]
readme = "README.md"
urls = { homepage = "https://github.com/connorbaker/bsrt" }
requires-python = ">=3.10"
dependencies = [
    "torch==1.13.0",
    "torchvision==0.14.0",
    "optuna==3.0.3",
    "pytorch-lightning==1.8.0.post1",
    "torchmetrics==0.10.2",
    "timm==0.6.11",
    "SQLAlchemy==1.4.42",
    "PyMySQL==1.0.2",
    "wandb==0.13.4",
    # Install LPIPS patched for newer version of torchvision
    "lpips @ git+https://github.com/ercanburak/PerceptualSimilarity.git@9606c353e5777fc95186a5a4c876e7c6a17651a6",
]

[project.optional-dependencies]
lint = ["black==22.10.0", "flake8==4.0.1", "isort==5.10.1", "pyright==1.1.279"]

[tool.black]
line-length = 99
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 99
py_version = "auto"

[tool.setuptools]
packages = ["bsrt"]

[tool.pyright]
include = ["bsrt"]
exclude = [
    "**/__pycache__",
    "bsrt/test_synthetic_burst.py",
    "bsrt/datasets/synthetic_burst/test_dataset.py",
    "bsrt/datasets/burstsr_dataset.py",
]
ignore = ["bsrt/loss", "bsrt/metrics"]
defineConstant = { DEBUG = true }
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.10"
pythonPlatform = "Linux"
