[build-system]
requires = ["setuptools >= 58.0", "cython", "wheel"]

[project]
name = "bsrt"
version = "0.1.0"
description = "Multi-frame super-resolution tool"
authors = [{ name = "Ziwei Luo", email = "ziwei.ro@gmail.com" }]
maintainers = [
    { name = "Ziwei Luo", email = "ziwei.ro@gmail.com" },
    { name = "Connor Baker", email = "connorbaker01@gmail.com" },
]
readme = "README.md"
urls = { homepage = "https://github.com/connorbaker/bsrt" }
requires-python = ">=3.8"
dependencies = [
    # PyTorch Lightning 1.8.0rc0
    "pytorch_lightning @ https://github.com/Lightning-AI/lightning/releases/download/1.8.0rc0/pytorch_lightning-1.8.0rc0-py3-none-any.whl",
    "torchmetrics @ https://github.com/Lightning-AI/metrics/releases/download/v0.10.1/torchmetrics-0.10.1-py3-none-any.whl",
    "timm==0.6.11",
    "ax-platform==0.2.8",
    "SQLAlchemy==1.4.42",
    "PyMySQL==1.0.2",
    "wandb==0.13.4",
    "bagua-cuda116==0.9.1",
    "redis==4.3.4",
    # Install LPIPS patched for newer version of torchvision
    "lpips @ git+https://github.com/ercanburak/PerceptualSimilarity.git@9606c353e5777fc95186a5a4c876e7c6a17651a6",
    # Install mosaicml with support for torchmetrics 0.10.0
    "mosaicml @ git+https://github.com/mosaicml/composer.git@59f02d1c79e251ce89604024046bc7edf45cc9c2",
]

[project.optional-dependencies]
lint = ["black==22.10.0", "flake8==4.0.1", "isort==5.10.1", "mypy==0.982"]

[tool.isort]
profile = "black"

[tool.setuptools]
packages = ["bsrt"]
