[build-system]
requires = ["setuptools >= 58.0", "cython", "wheel"]

[project]
name = "bsrt"
version = "0.1.0"
description = "Multi-frame super-resolution tool"
authors = [{ name = "Ziwei Luo", email = "ziwei.ro@gmail.com" }]
maintainers = [
    { name = "Ziwei Luo", email = "ziwei.ro@gmail.com" },
    { name = "Connor Baker", email = "connorbaker01@gmail.com" },
]
readme = "README.md"
urls = { homepage = "https://github.com/connorbaker/bsrt" }
requires-python = ">=3.8"
dependencies = [
    "pytorch-lightning==1.7.7",
    "torchmetrics==0.10.0",
    "timm==0.6.7",
    "pg8000==1.29.2",
    "wandb==0.13.4",
    # Install LPIPS patched for newer version of torchvision
    "lpips @ git+https://github.com/ercanburak/PerceptualSimilarity.git@9606c353e5777fc95186a5a4c876e7c6a17651a6",
    # Install mosaicml with support for torchmetrics 0.10.0
    "mosaicml @ git+https://github.com/mosaicml/composer.git@59f02d1c79e251ce89604024046bc7edf45cc9c2",

    "mypy==0.982",
    "black==22.10.0",
    "isort==5.10.1",
]

[project.optional-dependencies]
lint = ["flake8==4.0.1", "black==22.10.0", "isort==5.10.1"]

[tool.isort]
profile = "black"

[tool.setuptools]
packages = ["bsrt"]
