name: bsrt-real
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.7
  - pip==22.2.2

  # Pulls in cudatoolkit
  - pytorch==1.10.2=py3.7_cuda11.3_cudnn8.2.0_0
  - torchvision

  # For DCNv2
  - ninja==1.11.0
  - cupy
  - cuda-nvcc

  # Used to be installed by pip
  - matplotlib
  - imageio
  - opencv
  - tensorboardx
  - tqdm
  - timm
  - requests
  - exifread

  - pip:
    - torchsummaryX
    - pytorch-msssim
    - lpips
    - -e git+https://github.com/lbin/DCNv2.git@pytorch_1.9#egg=DCNv2
