name: bsrt
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - python=3.10
  - pip==22.2.2

  - pytorch==1.12.1=py3.10_cuda11.6_cudnn8.3.2_0
  - torchvision==0.13.1=py310_cu116
  - torchmetrics==0.9.3
  - cupy==11.1.0
  - nccl==2.14.3.1
  - opencv-python-headless==4.6.0.66
  - timm==0.6.7
  - gcsfs==2022.8.2
  - optuna==3.0.2
  - pip:
    - wandb==0.13.3
    - ray[all] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl

    # Use this fork of LPIPS until https://github.com/richzhang/PerceptualSimilarity/pull/114 is merged upstream
    - git+https://github.com/ercanburak/PerceptualSimilarity.git@9606c353e5777fc95186a5a4c876e7c6a17651a6#egg=lpips

    - git+https://github.com/Lightning-AI/metrics.git@9b19a922487e295810bf5e22a587727964cc8718#egg=torchmetrics