name: bsrt
channels:
  - pytorch
  - conda-forge
  - fastai
dependencies:
  - python==3.10.6

  - pytorch==1.12.1=py3.10_cuda11.6_cudnn8.3.2_0
  - torchvision==0.13.1=py310_cu116
  - torchmetrics==0.10.0
  - lpips==0.1.3

  - cupy==11.2.0
  - numpy==1.23.3
  - pandas==1.5.0

  - ray-core==2.0.0
  - ray-dashboard==2.0.0
  - ray-data==2.0.0
  - ray-tune==2.0.0

  - opencv-python-headless==4.6.0.66
  - timm==0.6.7
  # Waiting for https://github.com/fsspec/gcsfs/issues/498 in a new release
  - gcsfs==2022.7.1
  - optuna==3.0.2
  - wandb==0.13.4

  - black==22.8.0
