name: bsrt-mac
channels:
  - conda-forge
  - pytorch-nightly
  - fastai
dependencies:
  - python=3.10
  - pip==22.2.2

  # Must run nightlies to get the distributed backend
  - pytorch==1.14.0.dev20221007
  - torchvision==0.15.0.dev20221007
  - opencv==4.6.0
  - timm==0.6.7
  - gcsfs==2022.8.2
  - optuna==3.0.2

  # Note: Must manually uninstall grpcio from pip and install grpcio with conda
  # pip uninstall grpcio -y; micromamba install conda-forge::grpcio -y
  - pip:
    - wandb==0.13.3
    - ray[all]==2.0.0

    # Use this fork of LPIPS until https://github.com/richzhang/PerceptualSimilarity/pull/114 is merged upstream
    - git+https://github.com/ercanburak/PerceptualSimilarity.git@9606c353e5777fc95186a5a4c876e7c6a17651a6#egg=lpips

    - git+https://github.com/Lightning-AI/metrics.git@9b19a922487e295810bf5e22a587727964cc8718#egg=torchmetrics
