name: bsrt-nightly
channels:
  - nvidia
  - pytorch-nightly
  - conda-forge
  - fastai
dependencies:
  - conda-forge::python==3.10.6
  - conda-forge::pip==22.2.2

  - pytorch-nightly::pytorch==1.14.0.dev20221013=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-nightly::torchvision==0.15.0.dev20221013=py310_cu117
  - conda-forge::torchmetrics==0.10.0
  - conda-forge::lpips==0.1.3

  - nvidia::cuda==11.7.1
  - conda-forge::cupy==11.2.0
  - conda-forge::numpy==1.23.3
  - conda-forge::pandas==1.5.0

  - fastai::opencv-python-headless==4.6.0.66
  - fastai::timm==0.6.7
  # Waiting for https://github.com/fsspec/gcsfs/issues/498 in a new release
  - conda-forge::gcsfs==2022.7.1
  - conda-forge::optuna==3.0.3
  - conda-forge::wandb==0.13.4

  - conda-forge::black==22.10.0
  - conda-forge::isort==5.10.1
  - conda-forge::git==2.38.0
  - pip:
    - jsonargparse[signatures]==4.15.1
    - git+https://github.com/Lightning-AI/lightning.git@5dd7b6a4787819f12758a7d68d6c0cfdbed405c2