name: bsrt
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - python=3.7
  - pip==22.2.2

  - pytorch==1.12.1=py3.7_cuda11.6_cudnn8.3.2_0
  - torchvision==0.13.1=py37_cu116
  - pytorch-lightning==1.7.6
  - cupy==11.1.0

  - matplotlib
  - imageio
  - opencv-python-headless
  - tensorboardx
  - tqdm
  - timm
  - requests
  - exifread

  - pip:
    - bagua-cuda116
    - lpips
    - torchmetrics
    - torchsummaryX
