seed_everything: true
trainer:
  accelerator: auto
  strategy: null
  precision: bf16
  resume_from_checkpoint: null
  benchmark: true
  deterministic: false
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native