seed_everything: 1
trainer:
  accelerator: auto
  precision: bf16
  resume_from_checkpoint: null
  benchmark: true
  deterministic: false
  detect_anomaly: true
  plugins: null
  profiler: simple
  amp_backend: native
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      ddp_comm_state:
        class_path: torch.distributed.algorithms.ddp_comm_hooks.post_localSGD_hook.PostLocalSGDState
        init_args:
          process_group: null
          subgroup: null
          start_localSGD_iter: 8
      model_averaging_period: 4
      find_unused_parameters: true
      gradient_as_bucket_view: true
      static_graph: false
  callbacks:
    - class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: loss
        min_delta: 1e-2
        patience: 3
        mode: min
        strict: true
        check_finite: true
    - class_path: pytorch_lightning.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 1e-2
    - class_path: pytorch_lightning.callbacks.DeviceStatsMonitor
      init_args:
        cpu_stats: true
    - class_path: pytorch_lightning.callbacks.RichModelSummary
      init_args:
        max_depth: 1
    - class_path: pytorch_lightning.callbacks.RichProgressBar
      init_args:
        leave: true
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
        log_momentum: true
