seed_everything: 1
trainer:
  accelerator: auto
  precision: 16
  resume_from_checkpoint: null
  benchmark: true
  deterministic: false
  replace_sampler_ddp: true
  detect_anomaly: false
  plugins: null
  amp_backend: native
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      parallel_devices: null
      cluster_environment: null
      checkpoint_io: null
      precision_plugin: null
      ddp_comm_state:
        class_path: torch.distributed.algorithms.ddp_comm_hooks.post_localSGD_hook.PostLocalSGDState
        init_args:
          process_group: null
          subgroup: null
          start_localSGD_iter: 8
      find_unused_parameters: false
      model_averaging_period: 4
      check_reduction: false
      gradient_as_bucket_view: true
      static_graph: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: loss
        min_delta: 1e-2
        patience: 3
        mode: min
        strict: true
        check_finite: true
    - class_path: pytorch_lightning.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 1e-2
