seed_everything: 1
trainer:
  accelerator: auto
  resume_from_checkpoint: null
  max_epochs: 10
  limit_train_batches: 100
  limit_val_batches: 10
  check_val_every_n_epoch: 1
  val_check_interval: 1
  log_every_n_steps: 10

  # Speed related settings
  precision: 32
  benchmark: true
  deterministic: false
  detect_anomaly: false
  enable_progress_bar: false
  enable_model_summary: false
  enable_checkpointing: false
  replace_sampler_ddp: false
  logger: false

  amp_backend: native
  strategy:
    class_path: pytorch_lightning.strategies.DDPStrategy
    init_args:
      ddp_comm_state:
        class_path: torch.distributed.algorithms.ddp_comm_hooks.post_localSGD_hook.PostLocalSGDState
        init_args:
          start_localSGD_iter: 8
      model_averaging_period: 4

      # Speed-related settings
      find_unused_parameters: false
      gradient_as_bucket_view: true
      static_graph: true
